apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: laravel-app
          image: osama82/laravel-app:latest
          ports:
            - containerPort: 9000
          env:
            - name: APP_ENV
              value: production
            - name: APP_DEBUG
              value: "false"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: laravel-db-secret
                  key: host
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: laravel-db-secret
                  key: database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: laravel-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laravel-db-secret
                  key: password
